config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'books#index'
  get 'home/index'
  resources :books do
    resources :comments
  end
  devise_for :users, controllers: { registrations: 'registrations' }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.admin?
      can :manage, :all
    else
      can :update, Book do |book|
        book.user == user
      end
      can :destroy, Book do |book|
        book.user == user
      end
      can :create, Book
      can :create, Comment
    end




    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  def self.search(search)
    where("title LIKE ?", "%#{search}%")
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
              if params[:search]
                @books = Book.search(params[:search])
              else
                @books = Book.all
              end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    authorize! :update, @book
  end

  # POST /books
  # POST /books.json
  def create
    @user = current_user
    @book = @user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :resume, :user_id)
    end
end

app/controllers/comments_controllers.rb
class CommentsController < ApplicationController
  def create
    @user = current_user
    @book = @user.books.find(params[:post_id])
    @comments = @book.comments.create(comments_params)
    redirect_to book_path(@book)
  end

  def destroy
    @book = Mes_livre.find(params[:mes_livre_id])
    @comments = @book.comments.find(params[:id]).destroy
    redirect_to books_path(@book)
  end


  private

  def comments_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @book = Book.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def acount_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
    <br>
      <%= form_for(@book) do |f| %>
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %><br><br>
        <%= f.text_field :title, class: "form-control" %>
      </div><br>
      <div class="field">
        <%= f.label :author %><br><br>
        <%= f.text_field :author, class: "form-control" %>
      </div><br>
      <div class="field">
        <%= f.label :resume %><br><br>
        <%= f.text_area :resume, class: "form-control" %>
      </div><br>

    <br>
      <% if user_signed_in? %>
        <div class="actions text-center">
          <%= f.submit 'New book',class:'btn btn-success btn-mg' %>
        </div>
      <% else %>
        <div class="actions text-center">
          <%= link_to "New book", new_user_session_path, class:'btn btn-success btn-mg'  %>
        </div>
      <% end %>

  <% end %>

app/views/books/_form2.html.erb
    <br>
      <%= form_for(@book) do |f| %>
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %><br><br>
        <%= f.text_field :title, class: "form-control" %>
      </div><br>
      <div class="field">
        <%= f.label :author %><br><br>
        <%= f.text_field :author, class: "form-control" %>
      </div><br>
      <div class="field" >
        <%= f.label :resume %><br><br>
        <%= f.text_area :resume, class: "form-control", style:"height:150px;" %>
      </div><br>

    <br>

        <div class="actions text-center">
          <%= f.submit 'Update book',class:'btn btn-success btn-mg' %>
        </div>

  <% end %>

app/views/books/edit.html.erb
<div class="container ">
  <div class="row">
    <div class="col-xs-12"></div>
  </div>
  <div class="row ">
    <div class="col-xs-3"></div>
    <div class="col-xs-4">
      <h1 class="text-center">Editing Book</h1>
      <%= render 'form2' %>
      <br>
      <div class="text-center">
        <%= link_to 'Show', @book %>
        <%= link_to 'Back', books_path %>
      </div>
    </div>
    <div class="col-xs-5"></div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12"></div>
  </div>
  <div class="row">
    <div class="col-xs-3"></div>
    <div class="col-xs-6">
      <p id="notice"><%= notice %></p>
      <%= flash[:alert]%>
      <%=form_tag books_path, :method => 'get' do%>
        <p>
          <%= text_field_tag :search, params[:search], placeholder: "Search title", class: "form-control" %>
        </p>

      <%end%>
    </div>
    <div class="col-xs-3"></div>
  </div>
</div>



<div class="media">
  <div class="media-body">
    <table class="table table-hover ">
      <thead>
        <tr >

          <th class="text-center">Title</th>
          <th class="text-center">Author</th>
          <th class="text-center">Date of post</th>
          <th class="text-center">User</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
          <tr class="text-center">
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.updated_at.strftime "%Y-%m-%d" %></td>
            <td><%= book.user_id %></td>
            <td><%= link_to 'Show', book, class:'btn btn-primary btn-sm' %></td>
            <%if can? :update, book %>
              <td><%= link_to 'Edit', edit_book_path(book), class:'btn btn-warning btn-sm' %></td>
            <% end %>
            <%if can? :destroy, book %>
              <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm' %></td>
            <% end %>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>
<div class="container">
  <div class="row">
    <div class="col-xs-12"></div>
  </div>
  <div class="row">
    <div class="row">
      <div class="col-xs-4"></div>
      <div class="col-xs-4">
        <%= link_to 'New Book', new_book_path, class:'btn btn-success btn-lg' %>
        <%= link_to 'All books', books_path, class:'btn btn-primary btn-lg' %>
      </div>
      <div class="col-xs-4"></div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container ">
  <div class="row">
    <div class="col-xs-12"></div>
  </div>
  <div class="row ">
    <div class="col-xs-3"></div>
    <div class="col-xs-4">
      <h1 class="text-center">New Book</h1>
      <%= render 'form' %>
      <br>
      <div class="text-center">
        <%= link_to 'Back', books_path %>
      </div>
    </div>
    <div class="col-xs-5"></div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12"></div>
  </div>

  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-6">
      <p>
        <h4>Title</h4>

        <%= @book.title %>
      </p>
      <p>
        <h4>Author</h4>

        <%= @book.author %>
      </p>
      <p>
        <h4>Resume</h4>
        <br>
        <%= @book.resume %>
      </p>

    </div>
    <div class="col-xs-5 text-center">
      <%= form_for([@book, @book.comments.build]) do |f| %>
        <% if @book.errors.any? %>
          <p>Commentaires</p>
          <p> <%= @book.comments.content %>
          <%= link_to 'Supprimer', book_comment_path(book.comment, book), method: :delete %>
          </p>
        <% end %>
        <br>

        <h2> Ajouter un commentaire</h2>

        <div class="field">
          <%= f.text_area :content, class: "form-control" %>
        </div>
        <br>
        <div class="actions ">
          <%= f.submit 'Comment', class:'btn btn-success btn-lg' %>
        </div>
      <% end %>
    </div>

  </div>

  <div class="row" style="margin-bottom:50px;">
    <br>
    <div class="col-xs-1"></div>
    <div class="col-xs-3">
      <%= link_to 'Edit', edit_book_path(@book) , class:'btn btn-success btn-g'%>
    </div>
    <div class="col-xs-3">
      <%= link_to 'Back', books_path , class:'btn btn-danger btn-g'%>
    </div>
    <div class="col-xs-5"></div>
  </div>


</div>

app/views/home/index.html.erb
<div class="container ">
  <div class="row">
    <div class="col-xs-12"></div>
  </div>
  <div class="row ">
    <div class="col-xs-3"></div>
    <div class="col-xs-4">
      <h1 class="text-center">New Book</h1>
      <%= render 'books/form' %>
      <br>
      <div class="text-center">
        <%= link_to 'Back', books_path %>
      </div>
    </div>
    <div class="col-xs-5"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Library</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "home",  home_index_path  %></li>
      <li><%= link_to "books", root_path  %></li>
      <li><%= link_to "my books", root_path  %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "#{current_user.name}", edit_user_registration_path  %></li>
        <li><%= link_to "Déconexion", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "connexion", new_user_session_path  %></li>
        <li><%= link_to "rejoins nous", new_user_registration_path  %></li>
      <% end %>
    </ul>
  </div>
</nav>
<div class="container">

  <%= yield %>
</div>
</body>
</html>